// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainComponentManagement.Data;

#nullable disable

namespace TrainComponentManagement.Migrations
{
    [DbContext(typeof(TrainComponentDbContext))]
    [Migration("20250423090135_InitialCreateAndSeedData")]
    partial class InitialCreateAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainComponentManagement.Entities.TrainComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAssignQuantity")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UniqueNumber")
                        .IsUnique();

                    b.ToTable("TrainComponents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanAssignQuantity = false,
                            Name = "Engine",
                            UniqueNumber = "ENG123"
                        },
                        new
                        {
                            Id = 2,
                            CanAssignQuantity = false,
                            Name = "Passenger Car",
                            UniqueNumber = "PAS456"
                        },
                        new
                        {
                            Id = 3,
                            CanAssignQuantity = false,
                            Name = "Freight Car",
                            UniqueNumber = "FRT789"
                        },
                        new
                        {
                            Id = 4,
                            CanAssignQuantity = true,
                            Name = "Wheel",
                            Quantity = 0,
                            UniqueNumber = "WHL101"
                        },
                        new
                        {
                            Id = 5,
                            CanAssignQuantity = true,
                            Name = "Seat",
                            Quantity = 0,
                            UniqueNumber = "STS234"
                        },
                        new
                        {
                            Id = 6,
                            CanAssignQuantity = true,
                            Name = "Window",
                            Quantity = 0,
                            UniqueNumber = "WIN567"
                        },
                        new
                        {
                            Id = 7,
                            CanAssignQuantity = true,
                            Name = "Door",
                            Quantity = 0,
                            UniqueNumber = "DR123"
                        },
                        new
                        {
                            Id = 8,
                            CanAssignQuantity = true,
                            Name = "Control Panel",
                            Quantity = 0,
                            UniqueNumber = "CTL987"
                        },
                        new
                        {
                            Id = 9,
                            CanAssignQuantity = true,
                            Name = "Light",
                            Quantity = 0,
                            UniqueNumber = "LGT456"
                        },
                        new
                        {
                            Id = 10,
                            CanAssignQuantity = true,
                            Name = "Brake",
                            Quantity = 0,
                            UniqueNumber = "BRK789"
                        },
                        new
                        {
                            Id = 11,
                            CanAssignQuantity = true,
                            Name = "Bolt",
                            Quantity = 0,
                            UniqueNumber = "BLT321"
                        },
                        new
                        {
                            Id = 12,
                            CanAssignQuantity = true,
                            Name = "Nut",
                            Quantity = 0,
                            UniqueNumber = "NUT654"
                        },
                        new
                        {
                            Id = 13,
                            CanAssignQuantity = false,
                            Name = "Engine Hood",
                            UniqueNumber = "EH789"
                        },
                        new
                        {
                            Id = 14,
                            CanAssignQuantity = false,
                            Name = "Axle",
                            UniqueNumber = "AX456"
                        },
                        new
                        {
                            Id = 15,
                            CanAssignQuantity = false,
                            Name = "Piston",
                            UniqueNumber = "PST789"
                        },
                        new
                        {
                            Id = 16,
                            CanAssignQuantity = true,
                            Name = "Handrail",
                            Quantity = 0,
                            UniqueNumber = "HND234"
                        },
                        new
                        {
                            Id = 17,
                            CanAssignQuantity = true,
                            Name = "Step",
                            Quantity = 0,
                            UniqueNumber = "STP567"
                        },
                        new
                        {
                            Id = 18,
                            CanAssignQuantity = false,
                            Name = "Roof",
                            UniqueNumber = "RF123"
                        },
                        new
                        {
                            Id = 19,
                            CanAssignQuantity = false,
                            Name = "Air Conditioner",
                            UniqueNumber = "AC789"
                        },
                        new
                        {
                            Id = 20,
                            CanAssignQuantity = false,
                            Name = "Flooring",
                            UniqueNumber = "FLR456"
                        },
                        new
                        {
                            Id = 21,
                            CanAssignQuantity = true,
                            Name = "Mirror",
                            Quantity = 0,
                            UniqueNumber = "MRR789"
                        },
                        new
                        {
                            Id = 22,
                            CanAssignQuantity = false,
                            Name = "Horn",
                            UniqueNumber = "HRN321"
                        },
                        new
                        {
                            Id = 23,
                            CanAssignQuantity = false,
                            Name = "Coupler",
                            UniqueNumber = "CPL654"
                        },
                        new
                        {
                            Id = 24,
                            CanAssignQuantity = true,
                            Name = "Hinge",
                            Quantity = 0,
                            UniqueNumber = "HNG987"
                        },
                        new
                        {
                            Id = 25,
                            CanAssignQuantity = true,
                            Name = "Ladder",
                            Quantity = 0,
                            UniqueNumber = "LDR456"
                        },
                        new
                        {
                            Id = 26,
                            CanAssignQuantity = false,
                            Name = "Paint",
                            UniqueNumber = "PNT789"
                        },
                        new
                        {
                            Id = 27,
                            CanAssignQuantity = true,
                            Name = "Decal",
                            Quantity = 0,
                            UniqueNumber = "DCL321"
                        },
                        new
                        {
                            Id = 28,
                            CanAssignQuantity = true,
                            Name = "Gauge",
                            Quantity = 0,
                            UniqueNumber = "GGS654"
                        },
                        new
                        {
                            Id = 29,
                            CanAssignQuantity = false,
                            Name = "Battery",
                            UniqueNumber = "BTR987"
                        },
                        new
                        {
                            Id = 30,
                            CanAssignQuantity = false,
                            Name = "Radiator",
                            UniqueNumber = "RDR456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
